'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("TOZdbBackup.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /deb3Va7j1yGUY7on3xHYivIuX8sIsGGXMVhXUnYeqRCFbHlrmLOCh7/bL/X6lIyPTmJt40l1DP6+www7dAvWerDObuHaRdXA+cUKvH+toZJmhnbB0nYE8b1qkcX8Vv/ECwMLhaHlZU8CYlowARxT/PazfQIyz4rVuMfJ4PF1JGCWZmAdtCon79WCdJmN+q+WfnhPdFn7Lhf1A+kw4pJ1L3pg56HOkiakK3ISTSZIK25UjGSCuG83F1GFfROsNPkgZOFxMu2QrefNExDmLfHo9LdJgnLyTbCHAkeI7jEZJ0B/CExcHAA1i8mEr0k3pyIli5HiPlxg5bfhQslX1l8Cw==.
        '''</summary>
        Friend ReadOnly Property talentozrds_live_1() As String
            Get
                Return ResourceManager.GetString("talentozrds-live-1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /deb3Va7j1yGUY7on3xHYivIuX8sIsGGXMVhXUnYeqRCFbHlrmLOCh7/bL/X6lIyiRSA0jTuUTJsKyOsQKUYnL642hLd46dxjrzG4APCVCpwGCg5vDJW9Cs9PaWgQWho73PONdXU2r+ocPJR1zpZiJrIzhyZaCrr19zmMbT1U+DHKM4JbiuoSmYboGlqMAzXUkISWuiEVkGuH3F/QQfNVwqeSLqSdTt5e/Y9W1D6rDupjnkBBiBcMWBB7qBoCglXtx0ydIi0t2k3sV1kODfNi49OylTVEk/Ji3L0jtNZZgcRwUlq1a+FeQ6ya+4QX845D2rVQkS8GMzSp9P69q68ow==.
        '''</summary>
        Friend ReadOnly Property talentozrds_live_2() As String
            Get
                Return ResourceManager.GetString("talentozrds-live-2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /deb3Va7j1yGUY7on3xHYivIuX8sIsGGXMVhXUnYeqRCFbHlrmLOCh7/bL/X6lIyNWnaX0Z2NU34R7Ebq4GokqSdW/WtmhmUNJm448ClxGx+EgeD2r6oZufPqZ6n768SnyC0F9H7cVKWF6Uu6W/asFvTtW+g65nn19gLp+4LJWWFUGnno5IqzIczyGPt7okS+oY/emGgJQNy5A8KflpBLYs84qRn0u6chsl3IPCDpgPKWVP4m971zOdwy5y+tqeslcNqSnbd0RasDQ20qMX28ex6Qf/HGlnJ972Ob04lfflZ8SeDuttKcSeInIQCRpt6nYOI+Ekrnm0/ELM5+O1ZmA==.
        '''</summary>
        Friend ReadOnly Property talentozrds_live_3() As String
            Get
                Return ResourceManager.GetString("talentozrds-live-3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /deb3Va7j1yGUY7on3xHYivIuX8sIsGGXMVhXUnYeqRCFbHlrmLOCh7/bL/X6lIyXjsorQoiTT8xJASWykd0RJuLTyFqNCDNdBRlw6sPZ5Kj+UA3wzv/zcIqQ0mAEDwitUkGxrNM9TLsmzMV8xCMAqyZvF7Rv5AoC4+wvS+QHppYLkbXeEItH3Cy4IkErHsic1SuJiDyICm9PCXjF9fFagKXvaAUi6imOcrr8es0CWijcM/Ee24FPiGax42f25/7gjuUtUEh1Q15e9I+4ZwdcfQp3KyrNZWUUyJNaJhoqqzNupEZK8bqz1C3Z6RwL08BhXGCLApY44Eb9Buhz4O5vL2ToHEbInDruNVOqpqEHio=.
        '''</summary>
        Friend ReadOnly Property talentozrds_live_4() As String
            Get
                Return ResourceManager.GetString("talentozrds-live-4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /deb3Va7j1yGUY7on3xHYivIuX8sIsGGXMVhXUnYeqRCFbHlrmLOCh7/bL/X6lIygz42PFFVez8AhLkLOpiAZB8FVl4hxgmnZcKJoKDGzsVJSpxyHSvx3R1BCWXd85MaytpPHQu4yJiFE9FT+f84M4T9uj8zlJyDWEUhOM/7bdNI03eeGyjcwuiW/hrfOkOTBYkkksBN31z61PzDYIgltV4k3Q2HCR5tIyUL9Ta+kPik3FVVRowJg5kNvicOOGzdzQYU9Xy7QhG/mw/dvjkACrizbzvp1Zb/0DmJQJebbKbuQKssDMuvzFwjV+N934/HG0HUYyDDZgWUZtZK7rWJwCs0jO1SSafxf05eKOE+OQQpT4e9DFOzDOsjsb8EBvw9xpD39Sg3JIC/VO0/Tp8dKDCMksV6n3JfbrIYu5do957pRIltTPmgmtgJNC2GQnRw.
        '''</summary>
        Friend ReadOnly Property talentozrds_live_5() As String
            Get
                Return ResourceManager.GetString("talentozrds-live-5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /deb3Va7j1yGUY7on3xHYivIuX8sIsGGXMVhXUnYeqRCFbHlrmLOCh7/bL/X6lIyEEq9Hz8RJ4RaN5rcCaGXkC1hgcmPwgo4tRcwZB4+h3aR4/HetkCKGyLvX+wywFlWYN/V0gjYYnPs+leig9wC/90OfY7h2OCN17ab05UOdDkDG9aIbVIzAC7As0oFRvN4AGWKy43WZ3W453lN+/6gvqvDxTTn4X/V8bm+97PhqUmlba1CC2sjjn1O8Siv68NfFoL9cAw8mZU76TMn8usNR0K+xbbj44tAfSQzK+8umDEoQCEApSfRrzn0TQTq8pU1wFVhd7bSfou2Ig7UqgHnYeHRcRKs0jFMyv0+dHYN+5tWXjXcYoJ9xCICqeRQtAz4bKnoHs17c3Qm7NeTDpHo7GOAybKuMHNgK8qU7IUVJ88=.
        '''</summary>
        Friend ReadOnly Property talentozrds_live_6() As String
            Get
                Return ResourceManager.GetString("talentozrds-live-6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /deb3Va7j1yGUY7on3xHYivIuX8sIsGGXMVhXUnYeqThnshuObDuerOPEq9Onc4mbtmRQrl6uUc6v4vNFiZLGxGWyrptgsT8xUTMySYwLsxMSes29IO82tCx0xkTLqpnIc9UbgpDhC7KY+qrhhq9DOrWIwaULmfhDJ1xJ6VgfiDskkQ73GAe+RLQuUFNNOLNufFhxYaUW0qbT8I4bbrLPzLT+ZBLbazcTcXmXQm7xAu5K22eCCJZcFndxiLpF7J5fGNSxgdmEm20mQITCDEdIQ7dyW1za5BtLuXl5tQmCZ52DJ4YYZioJIRqIlzez7VV.
        '''</summary>
        Friend ReadOnly Property talentozrdsstage() As String
            Get
                Return ResourceManager.GetString("talentozrdsstage", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
